### ISSUE TITLE
راهنمایی

### ISSUE THREAD

**Issue by AliAryaeiNejad** [m-ahmadi/exref#1]
سلام

یک راهنمایی در مورد استفاده از لینکهای API میکنید؟

چه پارمترهایی به لینکها باید ارسال شود؟

https://github.com/m-ahmadi/exref/blob/master/tse/urls.txt
--------------------------------------------------------------------------------
rest API

... = :inscode/:deven

http://cdn.tsetmc.com/api/Instrument/GetInstrumentHistory/...		InstSimpleData

http://cdn.tsetmc.com/api/ClosingPrice/GetClosingPriceHistory/...	ClosingPriceData
http://cdn.tsetmc.com/api/BestLimits/...				BestLimitData
http://cdn.tsetmc.com/api/Trade/GetTradeHistory/.../:bool		IntraTradeData

http://cdn.tsetmc.com/api/ClientType/GetClientTypeHistory/...		ClientTypeData
http://cdn.tsetmc.com/api/MarketData/GetStaticThreshold/...		StaticTreshholdData
http://cdn.tsetmc.com/api/MarketData/GetInstrumentState/...		InstrumentStateData
http://cdn.tsetmc.com/api/Shareholder/...				ShareHolderData

http://cdn.tsetmc.com/api/ClosingPrice/GetClosingPriceDaily...		some info
--------------------------------------------------------------------------------

**Comment by m-ahmadi** [comment]
سلام،

تمام این  لینک های قسمت rest API دو پارامتر دریافت میکنن،

`inscode` کد داخلی نماد می باشد 
`deven` تاریخ میلادی به صورت یک عدد 8 رقمی 

مثلا کد داخلی نماد فولاد 46348559193224090 می باشد
و مثلا اگر اطلاعات روز بر فرض 20220221 را بخواهیم

http://cdn.tsetmc.com/api/Instrument/GetInstrumentHistory/46348559193224090/20220221

http://cdn.tsetmc.com/api/Instrument/GetInstrumentHistory/46348559193224090/20220221

http://cdn.tsetmc.com/api/ClosingPrice/GetClosingPriceHistory/46348559193224090/20220221

http://cdn.tsetmc.com/api/BestLimits/46348559193224090/20220221

فقط این `GetTradeHistory` یک پارامتر  `true` یا `false` هم میگیره
http://cdn.tsetmc.com/api/Trade/GetTradeHistory/46348559193224090/20220221/false

http://cdn.tsetmc.com/api/ClientType/GetClientTypeHistory/46348559193224090/20220221

http://cdn.tsetmc.com/api/MarketData/GetStaticThreshold/46348559193224090/20220221

http://cdn.tsetmc.com/api/MarketData/GetInstrumentState/46348559193224090/20220221

http://cdn.tsetmc.com/api/Shareholder/46348559193224090/20220221

http://cdn.tsetmc.com/api/ClosingPrice/GetClosingPriceDaily/46348559193224090/20220221

**Comment by AliAryaeiNejad** [comment]
چند تا سوال دیگه هم داشتم
1. برای قیمت لحظه ای، صف خرید و فروش و کلا معملات روز به چه آدرسی باید درخواست بدیم؟
2. مقدار  true و false  در GetTradeHistory کارش چیه؟

**Comment by m-ahmadi** [comment]
> 1. برای قیمت لحظه ای، صف خرید و فروش و کلا معملات روز به چه آدرسی باید درخواست بدیم؟


برای قیمت لحضه ایی،

http://www.tsetmc.com/tsev2/data/instinfofast.aspx?i=46348559193224090&c=27 

i = `InsCode` کد داخلي نماد
c = `CSecVal` کد گروه صنعت

اگر حرف آخر پارامتر سی یک علامت `+`باشه،
به معنی شامل شدن کدصنعت های بالاتر نیز هست، مثلا

`c=27+`


برای ریزمعاملات روز،
http://www.tsetmc.com/tsev2/data/TradeDetail.aspx?i=46348559193224090


<hr>

> 2. مقدار true و false در GetTradeHistory کارش چیه؟


مطمئن نیستم دقیقا، ولی وقتی فالس بدین دیتایی که بر میگردونه بیش از 2 برابر هست، و اگر مقایسه کنید دیتا رو می بینید که ردیف های  تکراری زیادی وجود داره.
